'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WhatsAppAPI
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WhatsAppAPI.IWhatsAppAPIs")>  _
    Public Interface IWhatsAppAPIs
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWhatsAppAPIs/TemplateBillingMessage", ReplyAction:="http://tempuri.org/IWhatsAppAPIs/TemplateBillingMessageResponse")>  _
        Function TemplateBillingMessage(ByVal phoneNumber As String, ByVal customerName As String, ByVal fileNamePdf As String, ByVal fileNameXml As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IWhatsAppAPIsChannel
        Inherits WhatsAppAPI.IWhatsAppAPIs, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WhatsAppAPIsClient
        Inherits System.ServiceModel.ClientBase(Of WhatsAppAPI.IWhatsAppAPIs)
        Implements WhatsAppAPI.IWhatsAppAPIs
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function TemplateBillingMessage(ByVal phoneNumber As String, ByVal customerName As String, ByVal fileNamePdf As String, ByVal fileNameXml As String) As String Implements WhatsAppAPI.IWhatsAppAPIs.TemplateBillingMessage
            Return MyBase.Channel.TemplateBillingMessage(phoneNumber, customerName, fileNamePdf, fileNameXml)
        End Function
    End Class
End Namespace
